### ISSUE TITLE
Constant CPU usage from service

### ISSUE THREAD

**Issue by kuklei** [EFTEC/Cyberarms#9]
I see a constant 25% CPU usage on the service. Once I stop it, then it of course drop. Is this normal?

Also I noticed that even the configuration window of the application (the main application) when opened keeps my CPU >40%.
![high CPU IDSS service](https://user-images.githubusercontent.com/48261728/65322547-73c7b500-dba7-11e9-881f-a75a78b1deff.png)
![high CPU IDSS Application](https://user-images.githubusercontent.com/48261728/65322548-73c7b500-dba7-11e9-8886-6ce13ec55a51.png)

Anything I need to do?

Attached also my system config. IDDS is 2.2.0
[DxDiag.txt](https://github.com/EFTEC/Cyberarms/files/3635602/DxDiag.txt)

**Comment by maxemilian** [comment]
Hi Kleidi

 

Please check you database size (cyberarms.idds.dbf) and the agents running. Disable network agents which are not needed because no ports are open (check for TLS/SSL, FTP, SMTP).

 

As network traffic is monitored, our product is likely to produce high CPU on systems with high network I/O

 

Max

 

Maxemilian Hilbrand (Software & Systeme)




CH: +41 71 511 722 0
AT (mobile): +43 660 703 92 54
 <mailto:maxemilian.hilbrand@isicore.com> maxemilian.hilbrand@isicore.com


isicore AG • Unterlettenstrasse 14 • CH-9443 Widnau
Gerichtsstandort CH-9450 Altstätten, UID CHE-110.354.078
Verwaltungsratspräsident: Maxemilian Hilbrand

 <http://www.isicore.com/> www.isicore.com I   <mailto:info@isicore.com> info@isicore.com

 

Von: Kleidi Kumbaro <notifications@github.com> 
Gesendet: Freitag, 20. September 2019 13:07
An: EFTEC/Cyberarms <Cyberarms@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [EFTEC/Cyberarms] Constant CPU usage from service (#9)

 

I see a constant 25% CPU usage on the service. Once I stop it, then it of course drop. Is this normal?

Also I noticed that even the configuration window of the application (the main application) when opened keeps my CPU >40%.
 <https://user-images.githubusercontent.com/48261728/65322547-73c7b500-dba7-11e9-881f-a75a78b1deff.png> 
 <https://user-images.githubusercontent.com/48261728/65322548-73c7b500-dba7-11e9-8886-6ce13ec55a51.png> 

Anything I need to do?

**Comment by kuklei** [comment]
Thanks Max for the reply. 
Agents activated were SQL, TLS, Windows base (not sure what this does), RRAS and Kerberos. After deleteting the DBF service with all the agents activated as before I see no CPU usage. Looks like indeed the DB size is the culprit. Any remedy to this?

Anyway, I was only seeing logs from TLS so I will keep only TLS and SQL as both RDP and SQL ports are open and I need to monitor those. 

Thanks

**Comment by dyakhnov** [comment]
Same issue here ;-(

 I have also noticed that CPU is high (>50%) if Admin panel is open on Start tab.

**Comment by maxemilian** [comment]
Hi Dmitry

 

Can you please check the database size in your Cyberarms directory?

 

Max

 

Maxemilian Hilbrand (Software & Systeme)




CH: +41 71 511 722 0
AT (mobile): +43 660 703 92 54
 <mailto:maxemilian.hilbrand@isicore.com> maxemilian.hilbrand@isicore.com


isicore AG • Unterlettenstrasse 14 • CH-9443 Widnau
Gerichtsstandort CH-9450 Altstätten, UID CHE-110.354.078
Verwaltungsratspräsident: Maxemilian Hilbrand

 

isicore GmbH • AT-6820 Frastanz

Gerichtsstandort AT-6800 Feldkirch, UID ATU74847339

Geschäftsführung: Nora Kuhn 

 <http://www.isicore.com/> www.isicore.com I   <mailto:info@isicore.com> info@isicore.com

 

Von: Dmitry Yakhnov <notifications@github.com> 
Gesendet: Donnerstag, 11. März 2021 05:14
An: EFTEC/Cyberarms <Cyberarms@noreply.github.com>
Cc: Maxemilian Hilbrand <maxemilian.hilbrand@isicore.de>; Comment <comment@noreply.github.com>
Betreff: Re: [EFTEC/Cyberarms] Constant CPU usage from service (#9)

 

Same issue here ;-(

I have also noticed that CPU is high (>50%) if Admin panel is open on Start tab.

**Comment by dyakhnov** [comment]
`cyberarms.idds.dbf` is 49MB with ~680K unsuccessful login attempts (most coming from Windows Base Security Agent and TLS/SSL Security Agent)

**Comment by kuklei** [comment]
@dyakhnov Delete the DBF file and reset the agents and you should be good to go
